# Generated by Django 4.2.10 on 2024-03-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoPet', models.CharField(max_length=50, verbose_name='Nome do Pet')),
                ('nomeDoDono', models.CharField(max_length=80, verbose_name='Nome do Dono')),
                ('telefone', models.CharField(max_length=15)),
                ('Dia', models.DateField(verbose_name='Dia da Reserva')),
                ('observaçoes', models.TextField(verbose_name='Observações')),
                ('tamanho', models.IntegerField(choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], verbose_name='Tamanho')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=25, verbose_name='Turno')),
            ],
        ),
    ]
