# Generated by Django 4.2.10 on 2024-04-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='Dia',
            new_name='dia',
        ),
    ]
