# Generated by Django 4.2.10 on 2024-05-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_petshop_reserva_pethop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='pethop',
            new_name='petshop',
        ),
        migrations.AlterField(
            model_name='petshop',
            name='bairro',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=5, verbose_name='Turno'),
        ),
    ]
