# Generated by Django 4.2.10 on 2024-03-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoPet', models.CharField(max_length=50, verbose_name='Nome do Pet')),
                ('Telefone', models.CharField(max_length=15)),
                ('Dia', models.DateField()),
                ('observaçoes', models.TextField(verbose_name='Observações')),
            ],
        ),
    ]
