# Generated by Django 4.2.10 on 2024-03-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Dia',
            field=models.DateField(verbose_name='Dia da Reserva'),
        ),
    ]
